### ISSUE TITLE
Windsurf: What about get version from APT repo?

### ISSUE THREAD

**Issue by sr-tream** [watzon/aur-packages#12]
We can load package version from the APT repo, like that:
```bash
curl -s https://windsurf-stable.codeiumdata.com/wVxQEIWkwPUEAGf3/apt/dists/stable/main/binary-amd64/Packages | grep -A 10 "Package: windsurf" | grep "Version:" | awk '{print $2}' | cut -d'-' -f1
```

And we can use this in `pkgver` function, like:
```bash
pkgver() {
    curl -s https://windsurf-stable.codeiumdata.com/wVxQEIWkwPUEAGf3/apt/dists/stable/main/binary-amd64/Packages | grep -A 10 "Package: windsurf" | grep "Version:" | awk '{print $2}' | cut -d'-' -f1
}
```

With that pkgver the PKGBUILD always downloads latest Windsurf version.

Updates can be checked via **paru** or other AUR-helpers, with similar functionality. It's helps users to have always latest version, when AUR package not updated

**Comment by watzon** [comment]
My github workflow is already getting the new version from the APT repo, but if you see something that needs to be updated by all means submit a PR
